name: Deplopy to Firebase Host
description: 'Deploy to Firebase Host'
inputs: 
  API_KEY:
    description: 'API Key'
    required: true
  AUTH_DOMAIN:
    description: 'Auth Domain'
    required: true
  DATABASE_URL:
    description: 'Database URL'
    required: true
  PROJECT_ID:
    description: 'Project ID'
    required: true
  FIREBASE_STORAGE_BUCKET:
    description: 'Storage Bucket'
    required: true
  FIREBASE_APP_ID:
    description: 'App ID'
    required: true
  GITHUB_TOKEN:
    description: 'Github Token'
    required: true
  FIREBASE_SERVICE_ACCOUNT:
    description: 'Firebase Service Account'
    required: true
  LIVESITE:
    description: 'Live Site'
    required: true

runs: 
  using: 'composite'
  steps:
    - name: Check if deploy to Live Site
      id: check_live_site
      run: echo "is_live=${{ inputs.liveSite == 'true' }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create .env File
      run: |
        touch .env
        echo "REACT_APP_FIREBASE_API_KEY=${{ inputs.API_KEY }}" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ inputs.AUTH_DOMAIN }}" >> .env
        echo "REACT_APP_FIREBASE_DATABASE_URL=${{ inputs.DATABASE_URL }}" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=${{ inputs.PROJECT_ID }}" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ inputs.FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "REACT_APP_FIREBASE_APP_ID=${{ inputs.FIREBASE_APP_ID }}" >> .env
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install yarn and build
      run: |
        yarn install
        yarn build
      shell: bash

    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ inputs.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ inputs.FIREBASE_SERVICE_ACCOUNT }}
        projectId: ${{ inputs.PROJECT_ID }}
        expires: ${EXPIRES}
        channelId: ${CHANNEL_ID}
        firebaseToolsVersion: 12.9.1
      env:
        EXPIRES: ${{ steps.check_live_site.outputs.is_live == 'false' && '30d' || '' }}
        CHANNEL_ID: ${{ steps.check_live_site.outputs.is_live == 'true' && 'live' || '' }}
    
    # - name: Check deploy to live site
    #   run: echo "Deploy to live site expires in ${EXPIRES} and is on channel ${CHANNEL_ID}"
    #   shell: bash
    #   env:
    #     EXPIRES: ${{ steps.check_live_site.outputs.is_live == 'false' && '30D' || '' }}
    #     CHANNEL_ID: ${{ steps.check_live_site.outputs.is_live == 'true' && 'live' || '' }}